modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "desertmania"
version = "${file.jarVersion}"
displayName = "DesertMania"
authors = "MCMania"
description = '''

'''
[[dependencies.desertmania]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.desertmania]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.desertmania]]
    modId = "skillsapi"
    mandatory = true
    versionRange = "[1.3]"
    ordering = "AFTER"
    side = "BOTH"
